import { useState, useEffect, useRef } from 'react';
import { useNavigate } from 'react-router-dom';
import { Plus, Search, Filter, FileText, Share2, ChevronDown, ChevronUp, Printer, ExternalLink, User } from 'lucide-react';
import { API } from '../api';

const STATUS_TABS = [
  { key: '', label: 'All', color: 'text-white/60' },
  { key: 'draft', label: 'Draft', color: 'text-amber-400' },
  { key: 'accepted', label: 'Accepted', color: 'text-emerald-400' },
  { key: 'paid', label: 'Paid', color: 'text-blue-400' },
  { key: 'converted', label: 'Converted', color: 'text-violet-400' },
];

const STATUS_BADGE = {
  draft: 'bg-amber-400/10 text-amber-400',
  accepted: 'bg-emerald-400/10 text-emerald-400',
  paid: 'bg-blue-400/10 text-blue-400',
  converted: 'bg-violet-400/10 text-violet-400',
};

export default function Quotes() {
  const navigate = useNavigate();
  const [quotes, setQuotes] = useState([]);
  const [loading, setLoading] = useState(true);
  const [filter, setFilter] = useState('');
  const [search, setSearch] = useState('');
  const [expandedId, setExpandedId] = useState(null);
  const [detail, setDetail] = useState(null);
  const printRef = useRef();

  useEffect(() => { loadQuotes(); }, []);

  async function loadQuotes() {
    try {
      const res = await API.getQuotes();
      setQuotes(res);
    } catch (e) { console.error(e); }
    finally { setLoading(false); }
  }

  async function loadDetail(id) {
    try {
      const res = await fetch(`/api/quotes/${id}/share`).then(r => r.json());
      setDetail(res);
    } catch (e) { console.error(e); }
  }

  async function shareQuote(id) {
    try {
      const res = await API.shareQuote(id);
      alert(`Share link copied! ${res.share_url}`);
    } catch (e) { alert('Failed: ' + e.message); }
  }

  async function updateStatus(id, status) {
    try {
      await API.updateQuoteStatus(id, status);
      loadQuotes();
      if (expandedId === id) loadDetail(id);
    } catch (e) { alert('Failed: ' + e.message); }
  }

  function handlePrint(quote) {
    const printWindow = window.open('', '_blank');
    const html = `
      <html><head><title>Quote #${quote.quote_token}</title><style>
        body{font-family:Arial,sans-serif;padding:40px;max-width:700px;margin:0 auto;color:#333}
        h1{font-size:24px;margin-bottom:8px} h2{font-size:14px;color:#666;margin-bottom:24px}
        table{width:100%;border-collapse:collapse;margin:20px 0} td{padding:10px 0;border-bottom:1px solid #eee}
        .label{color:#999;font-size:13px} .value{text-align:right;font-weight:600}
        .total{font-size:20px;font-weight:bold;text-align:right;margin-top:20px;padding-top:20px;border-top:2px solid #333}
        .footer{margin-top:40px;color:#999;font-size:12px;text-align:center}
      </style></head><body>
        <h1>CarpetCRM Quote</h1>
        <h2>Quote #${quote.quote_token} · ${quote.customer_name}</h2>
        <table>
          <tr><td class="label">Room</td><td class="value">${quote.room_name || '-'}</td></tr>
          <tr><td class="label">Dimensions</td><td class="value">${quote.room_width || 0}m × ${quote.room_length || 0}m</td></tr>
          <tr><td class="label">Product</td><td class="value">${quote.product_name || '-'}</td></tr>
          <tr><td class="label">Flooring</td><td class="value">£${(quote.product_price || 0).toFixed(2)}</td></tr>
          <tr><td class="label">Underlay</td><td class="value">£${(quote.underlay_price || 0).toFixed(2)}</td></tr>
          <tr><td class="label">Fitting</td><td class="value">£${(quote.fitting_price || 0).toFixed(2)}</td></tr>
          <tr><td class="label">Disposal</td><td class="value">£${(quote.disposal_price || 0).toFixed(2)}</td></tr>
          <tr><td class="label">Extras</td><td class="value">£${(quote.extras_price || 0).toFixed(2)}</td></tr>
        </table>
        <div class="total">Total: £${(quote.total || 0).toFixed(2)}</div>
        <div class="footer">Generated by CarpetCRM · carpetcrm.co.uk</div>
      </body></html>
    `;
    printWindow.document.write(html);
    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => printWindow.print(), 250);
  }

  const filtered = quotes.filter(q => {
    const matchesStatus = !filter || q.status === filter;
    const matchesSearch = !search || (q.customer_name || '').toLowerCase().includes(search.toLowerCase()) || (q.room_name || '').toLowerCase().includes(search.toLowerCase());
    return matchesStatus && matchesSearch;
  });

  const statusCounts = {};
  quotes.forEach(q => { statusCounts[q.status] = (statusCounts[q.status] || 0) + 1; });

  if (loading) {
    return (
      <div className="p-8 max-w-[1400px]">
        <div className="shimmer h-8 w-32 rounded-lg mb-4"></div>
        <div className="space-y-3">
          {[1,2,3].map(i => <div key={i} className="shimmer h-24 rounded-2xl"></div>)}
        </div>
      </div>
    );
  }

  return (
    <div className="p-8 max-w-[1400px]">
      <div className="flex items-center justify-between mb-8">
        <div>
          <p className="text-white/40 text-sm mb-1">Pricing & Proposals</p>
          <h1 className="text-3xl font-bold">Quotes</h1>
        </div>
        <button onClick={() => navigate('/customers')} className="btn-primary px-5 py-2.5 flex items-center gap-2 text-sm">
          <Plus className="w-4 h-4" /> New Quote
        </button>
      </div>

      <div className="flex items-center gap-4 mb-6">
        <div className="relative flex-1 max-w-sm">
          <Search className="w-4 h-4 absolute left-3 top-1/2 -translate-y-1/2 text-white/30" />
          <input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search quotes..." className="pl-10" />
        </div>
        <div className="flex gap-2">
          {STATUS_TABS.map(tab => (
            <button key={tab.key} onClick={() => setFilter(tab.key)}
              className={`px-3 py-1.5 rounded-full text-xs font-medium transition-colors ${
                filter === tab.key ? 'bg-white/10 text-white' : 'text-white/40 hover:text-white/60'
              }`}
            >
              {tab.label} {tab.key && `(${statusCounts[tab.key] || 0})`}
            </button>
          ))}
        </div>
      </div>

      <div className="space-y-3">
        {filtered.length === 0 ? (
          <div className="card glass p-12 text-center">
            <FileText className="w-12 h-12 text-white/10 mx-auto mb-4" />
            <p className="text-white/40 mb-2">No quotes found</p>
            <p className="text-sm text-white/20">{search || filter ? 'Try adjusting your filters' : 'Create a quote from a customer profile'}</p>
          </div>
        ) : (
          filtered.map(q => {
            const isExpanded = expandedId === q.id;
            return (
              <div key={q.id} className="card glass p-5 cursor-pointer" onClick={() => {
                if (isExpanded) { setExpandedId(null); setDetail(null); }
                else { setExpandedId(q.id); loadDetail(q.id); }
              }}>
                <div className="flex items-start justify-between">
                  <div className="flex items-center gap-3">
                    <div className="w-10 h-10 rounded-lg bg-white/5 flex items-center justify-center">
                      <User className="w-5 h-5 text-white/30" />
                    </div>
                    <div>
                      <div className="flex items-center gap-2">
                        <p className="font-semibold">{q.customer_name}</p>
                        <span className={`text-[10px] font-medium px-2 py-0.5 rounded-full ${STATUS_BADGE[q.status] || STATUS_BADGE.draft}`}>{q.status}</span>
                      </div>
                      <p className="text-xs text-white/40">{q.room_name} · {q.product_name}</p>
                    </div>
                  </div>
                  <div className="text-right">
                    <p className="text-lg font-bold text-amber-400">£{(q.total || 0).toFixed(2)}</p>
                    <p className="text-xs text-white/30">Margin £{(q.margin || 0).toFixed(2)}</p>
                  </div>
                </div>

                {isExpanded && detail && (
                  <div className="mt-5 pt-5 border-t border-white/[0.06]">
                    <div className="grid grid-cols-2 gap-4 mb-4">
                      <div className="space-y-2 text-sm">
                        <div className="flex justify-between"><span className="text-white/30">Room</span><span>{detail.room_name || '-'}</span></div>
                        <div className="flex justify-between"><span className="text-white/30">Dimensions</span><span>{detail.room_width || 0}m × {detail.room_length || 0}m</span></div>
                        <div className="flex justify-between"><span className="text-white/30">Product</span><span>{detail.product_name || '-'}</span></div>
                      </div>
                      <div className="space-y-2 text-sm">
                        <div className="flex justify-between"><span className="text-white/30">Flooring</span><span>£{(detail.product_price || 0).toFixed(2)}</span></div>
                        <div className="flex justify-between"><span className="text-white/30">Underlay</span><span>£{(detail.underlay_price || 0).toFixed(2)}</span></div>
                        <div className="flex justify-between"><span className="text-white/30">Fitting</span><span>£{(detail.fitting_price || 0).toFixed(2)}</span></div>
                        <div className="flex justify-between"><span className="text-white/30">Disposal</span><span>£{(detail.disposal_price || 0).toFixed(2)}</span></div>
                        <div className="flex justify-between"><span className="text-white/30">Extras</span><span>£{(detail.extras_price || 0).toFixed(2)}</span></div>
                        <div className="flex justify-between pt-2 border-t border-white/[0.06]"><span className="font-semibold">Total</span><span className="font-bold text-amber-400">£{(detail.total || 0).toFixed(2)}</span></div>
                      </div>
                    </div>

                    <div className="flex items-center gap-3">
                      <button onClick={e => { e.stopPropagation(); shareQuote(q.id); }} className="btn-secondary px-4 py-2 text-xs flex items-center gap-1.5">
                        <Share2 className="w-3.5 h-3.5" /> Share
                      </button>
                      <button onClick={e => { e.stopPropagation(); handlePrint(detail); }} className="btn-secondary px-4 py-2 text-xs flex items-center gap-1.5">
                        <Printer className="w-3.5 h-3.5" /> Print / PDF
                      </button>
                      <button onClick={e => { e.stopPropagation(); window.open(`/quote/${q.quote_token}`, '_blank'); }} className="btn-secondary px-4 py-2 text-xs flex items-center gap-1.5">
                        <ExternalLink className="w-3.5 h-3.5" /> View Online
                      </button>
                      {q.status === 'draft' && (
                        <button onClick={e => { e.stopPropagation(); updateStatus(q.id, 'accepted'); }} className="btn-primary px-4 py-2 text-xs">
                          Mark Accepted
                        </button>
                      )}
                      {q.status === 'accepted' && (
                        <button onClick={e => { e.stopPropagation(); navigate(`/orders?convert=${q.id}`); }} className="btn-primary px-4 py-2 text-xs">
                          Convert to Order
                        </button>
                      )}
                      {q.status === 'paid' && (
                        <button onClick={e => { e.stopPropagation(); updateStatus(q.id, 'converted'); }} className="btn-primary px-4 py-2 text-xs">
                          Convert to Order
                        </button>
                      )}
                    </div>
                  </div>
                )}
              </div>
            );
          })
        )}
      </div>
    </div>
  );
}
